# Generated by Django 4.1 on 2022-09-08 06:57

from django.db import migrations
from profiles.models import Account
import datetime


class Migration(migrations.Migration):

    def add_default_users(self, schema_editor):

        username = "codeuser"

        for count in range(1,3):
            current_username = username + str(count)

            # at least one object satisfying query exists
            if not Account.objects.filter(username = username).exists():
                Account.objects.create_user(email = current_username + "@test.com", username = current_username + str(count),
                 date_of_birth = datetime.date(1996, 11, 22), password = "testuserpassword")

            else:
                pass
            # no object satisfying query exists
        


    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_users, migrations.RunPython.noop)
    ]
