# Generated by Django 4.1 on 2022-09-08 06:57

from django.db import migrations
import datetime

class Migration(migrations.Migration):

    def add_default_users(apps, schema_editor):
        Account = apps.get_model("profiles", "Account")

        username = "codeuser"

        for count in range(1,3):
            current_username = username + str(count)

            Account.objects.atomic_create_user(email = current_username + "@test.com", username = current_username + str(count),
             date_of_birth = datetime.date(1996, 11, 22), password = "testuserpassword")

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_users, migrations.RunPython.noop)
    ]
