# Generated by Django 4.1 on 2022-08-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_bio_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
