# Generated by Django 4.1 on 2022-08-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_bio_id_alter_bio_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='username',
            new_name='uid',
        ),
    ]
