# Generated by Django 4.1 on 2022-08-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_username_bio_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='empty',
            field=models.TextField(blank=True, null=True),
        ),
    ]
