# Generated by Django 4.1 on 2022-08-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_bio_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='empty',
        ),
    ]
