# Generated by Django 4.1 on 2022-08-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_bio_empty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='uid',
            new_name='user',
        ),
    ]
